version: "3.9"

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8081 --reload
    volumes:
      - .:/app
    ports:
      - "8081:8081"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery:
    build: .
    command: celery -A internal.tasks.mail worker --loglevel=info --pool=solo
    volumes:
      - .:/app
    depends_on:
      - web
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env



  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
